version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app2
    ports:
      - "8000:8000"
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
      - /var/www/html/vendor
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: sh -c "php artisan serve --host=0.0.0.0 --port=8000 & php artisan queue:work"
    user: "1000:1000"
