services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-cli
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000

    user: ${UID}:${GID}
    depends_on: []
    dns:
      - 8.8.8.8
