services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        ports:
            - "8000:8000"
        user: "${UID:-1000}:${GID:-1000}"
        dns:
            - 8.8.8.8
